<a href="https://colab.research.google.com/github/hanmer33/Posco-Academy-personal-/blob/main/1_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [10]:
t=[i for i in range(1,13)]
tensor=tf.constant(t)

print("tensor:",tf.shape(tensor))
print("size:",tf.size(tensor))
print("rank:",tf.rank(tensor))

tensor: tf.Tensor([12], shape=(1,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [12]:
t1=[1,2,3]
print(type[t1])

t2=[3,4,5]
print(t1+t2)

t1=tf.constant(t1)
t2=tf.constant(t2)
print(t1+t2)

type[[1, 2, 3]]
[1, 2, 3, 3, 4, 5]
tf.Tensor([4 6 8], shape=(3,), dtype=int32)


In [18]:
tensor2d=tf.reshape(t,[3,4])
tensor2d[1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
tf.reshape(t,[3,2,2])

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [28]:
tensor3d=tf.reshape(t,[3,1,4])

In [23]:
x=tf.constant([1,0,-1,1])
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  0, -1,  1], dtype=int32)>

In [25]:
y=tf.expand_dims(x,0)

In [26]:
print(x.shape,y.shape)

(4,) (1, 4)


In [30]:
x1=tf.expand_dims(x,1)
x1

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 1],
       [ 0],
       [-1],
       [ 1]], dtype=int32)>

In [31]:
tensor3d

<tf.Tensor: shape=(3, 1, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]], dtype=int32)>

In [34]:
tf.matmul(tensor3d,x1)

<tf.Tensor: shape=(3, 1, 1), dtype=int32, numpy=
array([[[ 2]],

       [[ 6]],

       [[10]]], dtype=int32)>

In [35]:
tensor3d @ x1

<tf.Tensor: shape=(3, 1, 1), dtype=int32, numpy=
array([[[ 2]],

       [[ 6]],

       [[10]]], dtype=int32)>

In [36]:
mat=tf.constant([[1.0,2.0],[3.0,4.0]])
mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [38]:
tf.reduce_sum(mat)
tf.reduce_mean(mat)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [43]:
tf.reduce_sum(mat,1)
tf.reduce_mean(mat,1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [46]:
tf.Variable([[1.0,2.0],[3.0,4.0]])

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>